src/web/Models/Files/VideoFile.cs
using System.ComponentModel.DataAnnotations;
using EPiServer.Core;
using EPiServer.DataAnnotations;
using EPiServer.Framework.DataAnnotations;
using EPiServer.Web;

namespace OxxCommerceStarterKit.Web.Models.Files
{
    [ContentType(GUID = "85468104-E06F-47E5-A317-FC9B83D3CBA6")]
    [MediaDescriptor(ExtensionString = "flv,mp4,webm")]
    public class VideoFile : VideoData
    {
        /// <summary>
        /// Gets or sets the copyright.
        /// </summary>
        public virtual string Copyright { get; set; }

        /// <summary>
        /// Gets or sets the URL to the preview image.
        /// </summary>
        [UIHint(UIHint.Image)]
        public virtual ContentReference PreviewImage { get; set; }
   }
}

src/web/Controllers/ImageFileController.cs
/*
Commerce Starter Kit for EPiServer

All rights reserved. See LICENSE.txt in project root.

Copyright (C) 2013-2014 Oxx AS
Copyright (C) 2013-2014 BV Network AS

*/

using System.Web.Mvc;
using EPiServer.Globalization;
using EPiServer.Web;
using EPiServer.Web.Mvc;
using EPiServer.Web.Routing;
using OxxCommerceStarterKit.Web.Models.Blocks;
using OxxCommerceStarterKit.Web.Models.Files;
using OxxCommerceStarterKit.Web.Models.ViewModels;

namespace OxxCommerceStarterKit.Web.Controllers
{
    /// <summary>
    /// This controller is used when viewing an image in a content area. Mainly used in articles.
    /// </summary>
    public class ImageFileController : PartialContentController<ImageFile>
    {
        private readonly UrlResolver _urlResolver;

        public ImageFileController(UrlResolver urlResolver)
        {
            _urlResolver = urlResolver;
        }

		/// <summary>
		/// The index action for the image file. Creates the view model and renders the view.
		/// </summary>
		/// <param name="currentContent">The current image file.</param>
		public override ActionResult Index(ImageFile currentContent)
		{
			return Image(currentContent, string.Empty);
		}

        /// <summary>
        /// The index action for the image file. Creates the view model and renders the view.
        /// </summary>
        /// <param name="currentContent">The current image file.</param>
		/// <param name="extraImageUrlParameters">Text added to the url to the image</param>
        public ActionResult Image(ImageFile currentContent, string extraImageUrlParameters = null)
        {
			string extra = string.IsNullOrEmpty(extraImageUrlParameters) ? "" : extraImageUrlParameters;

			if (!string.IsNullOrEmpty(currentContent.VideoUrl))
			{
				string guessSource = currentContent.VideoUrl.ToLower();
				if (guessSource.Contains("viddler.com"))
				{
					var viddlerVideo = new ViddlerUrl(currentContent.VideoUrl);
					var viddlerModel = new VideoViewModel()
					{
						CoverImageUrl = _urlResolver.GetUrl(currentContent.ContentLink) + extra,
						HasCoverImage = true,
						IframeUrl = viddlerVideo.GetIframeUrl(true),
						IframeId = "viddler-" + viddlerVideo.Id
					};
					return PartialView("_Video", viddlerModel);
				}
				else if (guessSource.Contains("youtube"))
				{
					var youTubeVideo = new YouTubeUrl(currentContent.VideoUrl);
					var youTubeModel = new VideoViewModel()
					{
						CoverImageUrl = _urlResolver.GetUrl(currentContent.ContentLink) + extra,
						HasCoverImage = true,
						IframeUrl = youTubeVideo.GetIframeUrl(true)
					};
					return PartialView("_Video", youTubeModel);
				}
				else if (guessSource.Contains("vimeo.com"))
				{
					var vimeoVideo = new VimeoUrl(currentContent.VideoUrl);
					var vimeoModel = new VideoViewModel()
					{
						CoverImageUrl = _urlResolver.GetUrl(currentContent.ContentLink) + extra,
						HasCoverImage = true,
						IframeUrl = vimeoVideo.GetIframeUrl(true)
					};
					return PartialView("_Video", vimeoModel);
				}
			}

			var model = new ImageViewModel(currentContent, Language)
			{
				IsMobile = this.Request.Browser.IsMobileDevice,
				Tag = ControllerContext.ParentActionViewContext.ViewData["Tag"] as string
			};
            // Add additonal data to it
            model.Url += extra;

			return PartialView("~/Views/ImageFile/Index.cshtml", model);
        }

        public string Language
		{
			get
			{
			    string language = ControllerContext.RequestContext.GetLanguage();
				if (string.IsNullOrEmpty(language))
				{
					language = ContentLanguage.PreferredCulture.Name;
				}

				return language;
			}
		}
    }
}

src/web/Controllers/VideoFileController.cs
using System;
using System.Web.Mvc;
using EPiServer.Core;
using EPiServer.Web.Mvc;
using EPiServer.Web.Routing;
using OxxCommerceStarterKit.Web.Models.Files;
using OxxCommerceStarterKit.Web.Models.ViewModels;
using OxxCommerceStarterKit.Web.Extensions;

namespace OxxCommerceStarterKit.Web.Controllers
{
    /// <summary>
    /// Controller for the video file.
    /// </summary>
    public class VideoFileController : PartialContentController<VideoFile>
    {
        private readonly UrlResolver _urlResolver;

        public VideoFileController(UrlResolver urlResolver)
        {
            _urlResolver = urlResolver;
        }

        /// <summary>
        /// The index action for the video file. Creates the view model and renders the view.
        /// </summary>
        /// <param name="currentContent">The current video file.</param>
        public override ActionResult Index(VideoFile currentContent)
        {
            var model = new VideoViewModel
            {
                Url = _urlResolver.GetDefaultModeUrl(currentContent.ContentLink),
                CoverImageUrl = ContentReference.IsNullOrEmpty(currentContent.PreviewImage) ? String.Empty : _urlResolver.GetDefaultModeUrl(currentContent.PreviewImage),
            };
            
            // TODO: Over the top hacky
            return PartialView("/Views/Shared/DisplayTemplates/VideoFile.cshtml", model);
        }
    }
}

src/web/Views/Shared/DisplayTemplates/Address.cshtml
@model OxxCommerceStarterKit.Core.Objects.Address
@{
    Layout = null;
}
<div class="form-group">
    @Html.LabelFor(m => m.FirstName)
    @Html.EditorFor(m => m.FirstName, new { @class = "form-control firstname", disabled="disabled" })
</div>
<div class="form-group">
    @Html.LabelFor(m => m.LastName)
    @Html.EditorFor(m => m.LastName, new { @class = "form-control lastname", disabled="disabled" })
</div>
<div class="form-group">
    @Html.LabelFor(m => m.StreetAddress)
    @Html.EditorFor(m => m.StreetAddress, new { @class = "form-control streetaddress", disabled="disabled" })
</div>
<div class="form-inline">
    <div class="form-group">
        @Html.LabelFor(m => m.ZipCode)
        @Html.EditorFor(m => m.ZipCode, new { @class = "form-control zipcode", disabled="disabled" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.City)
        @Html.EditorFor(m => m.City, new { @class = "form-control city", disabled="disabled" })
    </div>
</div>

src/web/Views/Shared/DisplayTemplates/MediaFIle.cshtml
@using EPiServer.Core
@using EPiServer.ServiceLocation
@using EPiServer.Web.Routing
@using OxxCommerceStarterKit.Web.Models.Files
@model EPiServer.Core.ContentReference
@*See http://tedgustaf.com/blog/2014/4/render-image-properties-in-episerver-75/*@
@{
	Layout = null;
}
@if (!ContentReference.IsNullOrEmpty(Model))
{
	var contentLoader = ServiceLocator.Current.GetInstance<EPiServer.IContentLoader>();
	var content = contentLoader.Get<IContent>(Model);
	if (content != null && content is ImageFile)
	{
		var imageFile = (ImageFile)content;
	    @Html.Action("Image", "ImageFile", new { currentContent = imageFile, extraImageUrlParameters = ViewData["extraImageUrlParameters"] })
	    
	}
    else
    {
		@Image()
	}
}

@helper Image()
{
    <img src="@(ServiceLocator.Current.GetInstance<UrlResolver>().GetUrl(Model) + (ViewData["extraImageUrlParameters"]))" alt=""
         @(ViewData.ContainsKey("Width") ? "width='" + @ViewData["Width"] + "'" : "")
         @(ViewData.ContainsKey("Height") ? "height='" + @ViewData["Height"] + "'" : "")
         @(ViewData.ContainsKey("CssClass") ? "class='" + @ViewData["CssClass"] + "'" : "")
         @(ViewData.ContainsKey("CssStyle") ? "style='" + @ViewData["CssStyle"] + "'" : "") />
}

src/web/Views/Shared/DisplayTemplates/VideoFile.cshtml
@using EPiServer.Framework.Web.Resources
@model VideoViewModel
@{
    ClientResources.RequireScript(Href("~/scripts/jwplayer/jwplayer.js"));
    
    //The video element's ID needs to be unique in order for several video blocks and possible the same video block, to work on the same page
    var containerId = "video-container-" + Guid.NewGuid().GetHashCode();
}
@Html.FullRefreshPropertiesMetaData(new []{"Url"})
<div class="embed" id="embed" @Html.EditAttributes(m => m.Url)>
    <div style="position:absolute; width: 100%; height: 100%">
        <div id="@containerId"></div>
    </div>
    
    <script type="text/javascript">
        jwplayer('@containerId').setup({
            'file': @Html.Raw(Json.Encode(Model.Url)),
            'image': @Html.Raw(Json.Encode(Model.CoverImageUrl)),
            'type': 'video',
            'width': '100%',
            'height': '300px',
            'modes': [
                { type: 'html5' },
                { type: 'flash', src: "/scripts/jwplayer/player.swf" }
            ]
        });
        jwplayer('@containerId').play();
        jwplayer('@containerId').pause();
    </script>
</div>